### ISSUE TITLE
这项目有参考资料么, 可以分享一下?

### ISSUE THREAD

**Issue by isy-baicai** [sonichen/CloudNote#3]

**Comment by sonichen** [comment]
你好，仓库新增了说明文件，你可以看一下。
![image](https://github.com/sonichen/CloudNote/assets/57282299/3655cece-d7f2-4d69-8e7d-12c002701084)

**Comment by baicaiit** [comment]
好的, 非常感谢

**Comment by isy-baicai** [comment]
好的, 非常感谢
